services:
  apim:
    image: wso2/wso2am:4.3.0-alpine
    container_name: wso2-apim
    networks:
      - wso2-net
      - shared-network
    ports:
      - '9443:9443'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - RUNTIME_PROFILE=default
      - VIRTUAL_HOST=wso2-apim.rihal.dev
      - LETSENCRYPT_HOST=wso2-apim.rihal.dev
      - VIRTUAL_PORT=9443
      - VIRTUAL_PROTO=https
      - HOSTNAME=wso2-apim.rihal.dev
      - CARBON_HOST=wso2-apim.rihal.dev
      - CARBON_MGT_HOSTNAME=wso2-apim.rihal.dev
      - GATEWAY_ENV=Production
      - APIM_ANALYTICS_ENABLED=false
      - APIM_HOSTNAME=wso2-apim.rihal.dev
      - APIM_GATEWAY_HOSTNAME=wso2-apim.rihal.dev
      - APIM_KEYMANAGER_HOSTNAME=wso2-apim.rihal.dev
      - APIM_PUBLISHER_HOSTNAME=wso2-apim.rihal.dev
      - APIM_DEV_PORTAL_HOSTNAME=wso2-apim.rihal.dev
      - APIM_ADMIN_PORTAL_HOSTNAME=wso2-apim.rihal.dev
      - APIM_OAUTH2_CALLBACK_URL=https://wso2-apim.rihal.dev/publisher/services/auth/callback/login
      - APIM_OAUTH2_REDIRECT_URL=https://wso2-apim.rihal.dev/publisher/services/auth/callback/login
      - APIM_OAUTH2_ISSUER=https://wso2-apim.rihal.dev/oauth2/token
      - APIM_OAUTH2_AUTHORIZE_URL=https://wso2-apim.rihal.dev/oauth2/authorize
      - APIM_OAUTH2_TOKEN_URL=https://wso2-apim.rihal.dev/oauth2/token
      - APIM_OAUTH2_REVOKE_URL=https://wso2-apim.rihal.dev/oauth2/revoke
      - APIM_OAUTH2_INTROSPECT_URL=https://wso2-apim.rihal.dev/oauth2/introspect
      - APIM_OAUTH2_USERINFO_URL=https://wso2-apim.rihal.dev/oauth2/userinfo
      - APIM_OAUTH2_JWKS_URL=https://wso2-apim.rihal.dev/oauth2/jwks
      - APIM_OAUTH2_DCR_URL=https://wso2-apim.rihal.dev/oauth2/dcr/v1.1/register
      - APIM_OAUTH2_DCR_V1_URL=https://wso2-apim.rihal.dev/oauth2/dcr/v1.1/register
      - APIM_OAUTH2_DCR_V2_URL=https://wso2-apim.rihal.dev/oauth2/dcr/v1.1/register
      - APIM_OAUTH2_DCR_V3_URL=https://wso2-apim.rihal.dev/oauth2/dcr/v1.1/register
      - APIM_OAUTH2_DCR_V4_URL=https://wso2-apim.rihal.dev/oauth2/dcr/v1.1/register
      - APIM_OAUTH2_DCR_V5_URL=https://wso2-apim.rihal.dev/oauth2/dcr/v1.1/register
      - APIM_OAUTH2_DCR_V6_URL=https://wso2-apim.rihal.dev/oauth2/dcr/v1.1/register
      - APIM_OAUTH2_DCR_V7_URL=https://wso2-apim.rihal.dev/oauth2/dcr/v1.1/register
      - APIM_OAUTH2_DCR_V8_URL=https://wso2-apim.rihal.dev/oauth2/dcr/v1.1/register
      - APIM_OAUTH2_DCR_V9_URL=https://wso2-apim.rihal.dev/oauth2/dcr/v1.1/register
      - APIM_OAUTH2_DCR_V10_URL=https://wso2-apim.rihal.dev/oauth2/dcr/v1.1/register
    volumes:
      - esb_repo:/home/wso2carbon/repository/deployment/server

  esb:
    image: wso2/wso2ei-integrator:latest
    container_name: wso2-esb
    networks:
      - wso2-net
      - shared-network
    ports:
      - '8290:8290'
      - '8243:8243'
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - VIRTUAL_HOST=wso2-esb.rihal.dev
      - VIRTUAL_PORT=8290
      - VIRTUAL_PROTO=https
    volumes:
      - esb_repo:/home/wso2carbon/repository/deployment/server

  postgres:
    image: postgres:13
    container_name: postgres
    networks:
      - wso2-net
      - shared-network
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - wso2-net
    ports:
      - '5672:5672'
      - '15672:15672'

  mockapi:
    image: kennethreitz/httpbin
    container_name: mockapi
    networks:
      - wso2-net
      - shared-network
    ports:
      - '8000:80'

  loki:
    image: grafana/loki:2.4.1
    container_name: loki
    networks:
      - wso2-net
      - shared-network
    volumes:
      - loki_data:/loki
    ports:
      - '3100:3100'

  promtail:
    image: grafana/promtail:2.4.1
    container_name: promtail
    networks:
      - wso2-net
      - shared-network
    volumes:
      - .:/etc/promtail/
    command: -config.file=/etc/promtail/promtail-config.yml

  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    networks:
      - wso2-net
      - shared-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:9.2.1
    container_name: grafana
    networks:
      - wso2-net
      - shared-network
    ports:
      - '${GRAFANA_PORT}:3000'
    environment:
      - VIRTUAL_HOST=wso2-grafana.rihal.dev
      - LETSENCRYPT_HOST=wso2-grafana.rihal.dev
      - VIRTUAL_PORT=${GRAFANA_PORT}
      - VIRTUAL_PROTO=https
    depends_on:
      - prometheus
      - loki

volumes:
  postgres_data:
  esb_repo:
  loki_data:

networks:
  wso2-net:
    driver: bridge
  shared-network:
    external: true
