global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: wso2-apim
    metrics_path: /metrics
    static_configs:
      - targets: ["apim:9443"]
    scheme: https
    tls_config:
      insecure_skip_verify: true  # Disable TLS verification for simplicity

  - job_name: wso2-esb
    metrics_path: /metrics
    static_configs:
      - targets: ["esb:8290"]

  - job_name: rabbitmq
    metrics_path: /metrics
    static_configs:
      - targets: ["rabbitmq:15672"]

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]  # Optional: Add if you deploy node-exporter

  - job_name: loki
    static_configs:
      - targets: ["loki:3100"]
