server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: dockerlogs
          __path__: /var/lib/docker/containers/**/*.log
          host: ${HOSTNAME}

  - job_name: wso2
    static_configs:
      - targets:
          - localhost
        labels:
          job: wso2logs
          __path__: /home/wso2carbon/repository/deployment/server/**/*.log
          host: ${HOSTNAME}
